# NUMPY

## Introduction
Short paragraph on what NumPy is and why it’s useful.

**Example:**

“NumPy is a fundamental library for scientific computing in Python. It provides fast and memory-efficient arrays along with mathematical functions for data science, machine learning, and numerical simulations.”

## Importing NumPy

In [2]:
import numpy as np

### Array Creation
* Creating arrays from lists
* Using built-in functions (np.zeros, np.ones, np.arange, np.linspace)
* Multidimensional arrays

We can create NumPy arrays from Python lists using `np.array()`.  
This is the most common way to start working with arrays.

In [8]:
# Create a NumPy array from a Python list
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr)

1D Array: [1 2 3 4 5]


In [9]:
# Create a 2D array of zeros
zeros_arr = np.zeros((2, 3))
print("2D Zeros Array:\n", zeros_arr)

2D Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Create an array with values from 0 to 9
range_arr = np.arange(10)
print("Range Array:", range_arr)

Range Array: [0 1 2 3 4 5 6 7 8 9]


### Array Operations
* Element-wise operations
* Broadcasting
* Universal functions (np.add, np.multiply, np.sqrt, etc.)

NumPy supports element-wise operations.  
That means operations apply to each element without using loops.

In [11]:
# Element-wise addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)

Addition: [5 7 9]


In [12]:
# Broadcasting
print("Broadcasting example:", a + 10)

Broadcasting example: [11 12 13]


In [13]:
# Using universal functions
print("Square roots:", np.sqrt(a))

Square roots: [1.         1.41421356 1.73205081]


### Indexing and Slicing
* Accessing single elements
* Slicing sub-arrays
* Boolean indexing

We can access elements using indexes (arr[0]) or slices (arr[1:4]).  
Slicing creates a view, not a copy.

In [14]:
arr = np.array([10, 20, 30, 40, 50])
print("First element:", arr[0])
print("Slice [1:4]:", arr[1:4])
# Boolean indexing
print("Elements greater than 25:", arr[arr > 25])

First element: 10
Slice [1:4]: [20 30 40]
Elements greater than 25: [30 40 50]


### Array Statistics
* Mean, median, standard deviation
* Min, max, sum

np.mean(arr) → Returns the average of all elements.  
np.median(arr) → Middle value when data is sorted.  
np.std(arr) → Measures spread of values (standard deviation).  
np.min(arr) / np.max(arr) → Smallest and largest values.  
np.sum(arr) → Adds up all elements.

In [15]:
arr = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Sum:", np.sum(arr))

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Min: 1
Max: 5
Sum: 15


## Linear Algebra Operations
* Matrix multiplication (np.dot, @)
* Transpose
* Determinant and inverse

We can calculate the determinant of a matrix using np.linalg.det().  
The inverse of a matrix (if it exists) is found using np.linalg.inv().  
Not every matrix has an inverse: only square and non-singular matrices do.
### Matrix Multiplication: `np.dot` vs `@`

- `np.dot(A, B)` → behaves differently depending on dimensions:  
  - For 1D vectors → computes the dot product.  
  - For 2D arrays → performs matrix multiplication.  
- `A @ B` → introduced in Python 3.5, is the **matrix multiplication operator**.  
  - Equivalent to `np.matmul(A, B)`.  
  - Always follows matrix multiplication rules.  

👉 For **2D arrays**, both `np.dot(A, B)` and `A @ B` give the same result.  


In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix multiplication:\n", np.dot(A, B))
print("Matrix multiplication:\n", A @ B)
print("Transpose of A:\n", A.T)
print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))

Matrix multiplication:
 [[19 22]
 [43 50]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### Random Numbers
* Random integers, floats
* Random distributions

NumPy provides the np.random module for generating random numbers.  
We can create random integers using np.random.randint().  
For random floats, use np.random.rand() or np.random.randn().  
Useful for simulations, testing, and machine learning.

In [17]:
rand_ints = np.random.randint(1, 10, size=5)
print("Random integers:", rand_ints)
rand_norm = np.random.randn(3, 3)
print("Random normal distribution:\n", rand_norm)

Random integers: [3 8 7 5 3]
Random normal distribution:
 [[-0.67227271  2.57702668  0.71709986]
 [-0.86563984  0.64305449 -0.55658718]
 [ 0.8380881  -1.52904191 -1.56645717]]


### Additional Array Creation Methods
- **np.arange(start, stop, step)** → Creates evenly spaced values within an interval.
- **np.ones(shape)** → Creates an array of ones.
- **np.zeros(shape)** → Creates an array of zeros.
- **np.identity(n)** → Creates an identity matrix of size n×n.


In [18]:
arr1 = np.arange(0, 10, 2)
print("np.arange(0, 10, 2):\n", arr1)

arr2 = np.ones((3, 3))
print("\nnp.ones((3,3)):\n", arr2)

arr3 = np.zeros((2, 4))
print("\nnp.zeros((2,4)):\n", arr3)

arr4 = np.identity(4)
print("\nnp.identity(4):\n", arr4)

np.arange(0, 10, 2):
 [0 2 4 6 8]

np.ones((3,3)):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

np.zeros((2,4)):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.identity(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Reshaping Arrays
NumPy allows us to change the shape of arrays using `reshape()`. The new shape must be compatible with the total number of elements.


In [6]:
a = np.arange(12)
print("Original array:", a)
print("Reshaped to 3x4:\n", a.reshape(3,4))
print("Reshaped to 2x2x3:\n", a.reshape(2,2,3))

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


### Flatten vs Ravel
- `flatten()` returns a **copy** of the array collapsed into one dimension.
- `ravel()` returns a **view** of the array whenever possible (more memory efficient).


In [7]:
A = np.array([[1, 2], [3, 4]])
flat = A.flatten()
rav = A.ravel()

print("Original Array:\n", A)
print("\nA.flatten():", flat)
print("A.ravel():", rav)

# Let's modify the original array to see the difference
A[0,0] = 99
print("\nModified Original Array:\n", A)
print("Flatten result (unchanged):", flat)
print("Ravel result (view):", rav)

Original Array:
 [[1 2]
 [3 4]]

A.flatten(): [1 2 3 4]
A.ravel(): [1 2 3 4]

Modified Original Array:
 [[99  2]
 [ 3  4]]
Flatten result (unchanged): [1 2 3 4]
Ravel result (view): [99  2  3  4]


## Conclusion
Wrap up with a short summary.

**Example:**

“In this notebook, we explored NumPy basics including array creation, operations, slicing, statistics, and linear algebra. NumPy is the backbone of libraries like Pandas, SciPy, and Scikit-learn, so mastering it is an essential first step in data science.”

In [29]:
m1 = np.array([[1,2],[3,4]])
m1 * 2

array([[2, 4],
       [6, 8]])

In [30]:
m2 = np.arange(1,13)
m2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
m3 = np.arange(9)
m3 = m3.reshape(3,3)
m3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
m3.shape

(3, 3)

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones((3,2)) * 5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [36]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
l1 = np.arange(12).reshape(3,4)
l1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
l1[1,1]

np.int64(5)

In [40]:
l1[0,1:3]

array([1, 2])

In [41]:
l1[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [42]:
l1[0:3,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [43]:
l1[:,1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [44]:
l1 = np.arange(12).reshape(3,4)
l1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [45]:
l1[l1 < 6]

array([0, 1, 2, 3, 4, 5])

In [46]:
l1 = np.arange(12).reshape(3,4)
l1 + 4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
l1[l1 % 2 == 0].reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [48]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
a + b

array([3, 4, 5])

In [49]:
A = np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
B = np.arange(12).reshape(3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
A * B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [52]:
B = B.reshape(4,3)
B

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
np.matmul(A, B)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [54]:
A @ B

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [55]:
B @ A

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [56]:
np.dot(A, B)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [57]:
B = B.reshape(3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
A @ B.T

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [59]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [62]:
np.matmul(a,A)

array([32, 38, 44, 50])

In [64]:
a = np.arange(3)
a.T

array([0, 1, 2])

In [65]:
a = np.arange(3).reshape(1,3)
a.T

array([[0],
       [1],
       [2]])

In [66]:
v = np.arange(3)
v

array([0, 1, 2])

In [67]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
np.dot(v,A)

array([20, 23, 26, 29])

In [71]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [72]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
A.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
A.shape

(3, 4)

In [80]:
A.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [81]:
A.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [83]:
B = np.arange(24).reshape(2, 3, 4)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [86]:
B[1,1,1]

np.int64(17)

In [112]:
A = np.arange(12).reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [113]:
B = np.arange(3).reshape(1,3)
B

array([[0, 1, 2]])

In [114]:
print(A.shape,B.shape)

(4, 3) (1, 3)


In [115]:
A + B

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [116]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
B.T

array([[0],
       [1],
       [2]])

In [118]:
A + B.T

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [119]:
A * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [123]:
np.random.randint(1,100,5)

array([50, 78,  4, 35,  3])

In [124]:
np.random.rand(3)

array([0.00236141, 0.62749494, 0.27053785])

In [125]:
50 + np.random.rand() * 25

71.88168779772931

In [127]:
import matplotlib.pyplot as plt

In [133]:
mean = 100
std = 15
np.random.normal(mean, std, 100)

array([110.86145353,  82.11057933,  81.94608718,  81.37018845,
       111.60287238, 106.38245105,  72.52864886, 103.14000864,
       119.9993196 , 113.79809275, 100.30946151,  68.78192386,
       114.4903033 ,  99.09771793, 137.39669135,  81.6298474 ,
        94.39172034,  93.12904041,  86.9721094 ,  85.07543818,
        95.61807655,  89.71893818,  95.20114215,  74.05776092,
        80.12421361, 108.71913025, 112.53897514,  96.33872833,
        90.62233152, 121.58672045,  97.12509446, 100.80487211,
        85.32065471,  75.65100541, 105.93142768, 140.07675328,
        97.25095767, 103.49906912,  79.12322217, 111.00731424,
       100.40564446, 114.08838731,  99.86660724, 137.62620583,
       100.21891645, 104.4253881 , 111.73435457,  96.27196945,
        88.41793567, 120.54558718,  95.80626948, 114.08305657,
        92.81231932, 100.75378525,  85.34993065,  58.44722454,
       118.37886004, 110.63755437, 126.07252871, 106.58952038,
       100.22119391, 112.67614674, 100.1079789 ,  74.53

In [134]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [135]:
b = a.reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [136]:
c = a * 2
c

array([0, 2, 4, 6])

In [137]:
a[0] = 100
a

array([100,   1,   2,   3])

In [138]:
b

array([[100,   1],
       [  2,   3]])

In [139]:
c

array([0, 2, 4, 6])

In [140]:
a[a>2]

array([100,   3])

In [141]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
np.sum(a)

np.int64(66)

In [146]:
np.sum(a,axis=0)

array([12, 15, 18, 21])

In [147]:
np.sum(a,axis=1)

array([ 6, 22, 38])

In [148]:
np.mean(a,axis=0)

array([4., 5., 6., 7.])

In [149]:
np.median(a,axis=0)

array([4., 5., 6., 7.])